export const Components = {
  CART: 'CART',
  CITIES: 'CITIES',
  HINTS: 'HINTS',
  MENU: 'MENU',
  OFFERS: 'OFFERS',
  ARTICLES: 'ARTICLES',
  SHARES: 'SHARES',
  LINKS: 'LINKS',
  COMPLEXES: 'COMPLEXES',
  FEATURES: 'FEATURES',
  MAP: 'MAP',
  SPECIALISTS: 'SPECIALISTS',
  SEARCH: 'SEARCH',
  SPECIALISTS_FILTER: 'SPECIALISTS_FILTER',
  DISCOUNTS: 'DISCOUNTS',
};

export default Components;
